import { useEffect, useState } from 'react';
import api from './services/api.js';

const emptyForm = { date: '', startTime: '19:00', endTime: '21:00', partySize: 2 };
const errorText = (error) => error.response?.data?.message || 'Something went wrong. Is the backend running?';

function Auth({ onLogin }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ name: '', email: '', password: '' });
  const [message, setMessage] = useState('');
  async function submit(event) { event.preventDefault(); setMessage(''); try { const { data } = await api.post(`/auth/${mode}`, form); localStorage.setItem('restaurant_token', data.data.token); onLogin(data.data.user); } catch (error) { setMessage(errorText(error)); } }
  return <main className="auth-layout"><section className="auth-intro"><p className="eyebrow">TABLE & THYME</p><h1>A good table makes the evening.</h1><p>Reserve your place with a few simple details, then let the kitchen do the rest.</p></section><form className="panel auth-panel" onSubmit={submit}><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'JOIN THE TABLE'}</p><h2>{mode === 'login' ? 'Sign in' : 'Create account'}</h2>{mode === 'register' && <label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{message && <p className="alert">{message}</p>}<button className="primary">{mode === 'login' ? 'Sign in' : 'Register'}</button><button type="button" className="link-button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage(''); }}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></form></main>;
}

function ReservationForm({ onCreated }) {
  const [form, setForm] = useState(emptyForm); const [tables, setTables] = useState([]); const [selected, setSelected] = useState(''); const [message, setMessage] = useState('');
  const update = (key, value) => setForm({ ...form, [key]: value });
  async function search(event) { event.preventDefault(); setMessage(''); try { const { data } = await api.get('/tables/available', { params: form }); setTables(data.data.tables); setSelected(''); if (!data.data.tables.length) setMessage('No tables match that time and party size.'); } catch (error) { setMessage(errorText(error)); } }
  async function reserve() { if (!selected) return setMessage('Choose an available table first.'); try { await api.post('/reservations', { ...form, reservationDate: form.date, table: selected }); setMessage('Reservation confirmed.'); setTables([]); setSelected(''); onCreated(); } catch (error) { setMessage(errorText(error)); } }
  return <section className="panel"><div className="section-heading"><div><p className="eyebrow">PLAN A VISIT</p><h2>Find your table</h2></div><span className="pill">Live availability</span></div><form className="form-grid" onSubmit={search}><label>Date<input required type="date" value={form.date} onChange={e => update('date', e.target.value)} /></label><label>Start<input required type="time" value={form.startTime} onChange={e => update('startTime', e.target.value)} /></label><label>End<input required type="time" value={form.endTime} onChange={e => update('endTime', e.target.value)} /></label><label>Guests<input required min="1" type="number" value={form.partySize} onChange={e => update('partySize', e.target.value)} /></label><button className="primary">Search tables</button></form>{message && <p className="alert">{message}</p>}{tables.length > 0 && <div className="table-choices">{tables.map(table => <button type="button" className={`table-choice ${selected === table._id ? 'selected' : ''}`} key={table._id} onClick={() => setSelected(table._id)}><strong>Table {table.tableNumber}</strong><span>{table.capacity} seats · {table.location}</span></button>)}<button className="primary confirm" onClick={reserve}>Confirm reservation</button></div>}</section>;
}

function CustomerHome({ refresh, setRefresh }) {
  const [reservations, setReservations] = useState([]);
  async function load() { try { const { data } = await api.get('/reservations/my'); setReservations(data.data.reservations); } catch { setReservations([]); } }
  useEffect(() => { load(); }, [refresh]);
  async function cancel(id) { await api.delete(`/reservations/${id}`); setRefresh(refresh + 1); }
  return <><ReservationForm onCreated={() => setRefresh(refresh + 1)} /><section className="panel"><div className="section-heading"><div><p className="eyebrow">YOUR EVENINGS</p><h2>My reservations</h2></div></div>{reservations.length ? <div className="reservation-list">{reservations.map(item => <article className="reservation-row" key={item._id}><div><strong>{item.reservationDate} · {item.startTime}–{item.endTime}</strong><span>Table {item.table?.tableNumber} · {item.partySize} guests · {item.table?.location}</span></div><div><span className={`status ${item.status}`}>{item.status}</span>{item.status === 'confirmed' && <button className="text-button" onClick={() => cancel(item._id)}>Cancel</button>}</div></article>)}</div> : <p className="muted">Your confirmed reservations will appear here.</p>}</section></>;
}

function AdminHome() {
  const [tables, setTables] = useState([]); const [reservations, setReservations] = useState([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [form, setForm] = useState({ tableNumber: '', capacity: '', location: '' }); const [message, setMessage] = useState('');
  async function load() { const [tableResponse, reservationResponse] = await Promise.all([api.get('/tables'), api.get('/reservations', { params: { date } })]); setTables(tableResponse.data.data.tables); setReservations(reservationResponse.data.data.reservations); }
  useEffect(() => { load().catch(error => setMessage(errorText(error))); }, [date]);
  async function addTable(event) { event.preventDefault(); try { await api.post('/tables', { ...form, tableNumber: Number(form.tableNumber), capacity: Number(form.capacity) }); setForm({ tableNumber: '', capacity: '', location: '' }); setMessage('Table added.'); load(); } catch (error) { setMessage(errorText(error)); } }
  async function updateTable(table) { const capacity = window.prompt('Capacity', table.capacity); const location = window.prompt('Location', table.location); if (!capacity || !location) return; try { await api.put(`/tables/${table._id}`, { capacity: Number(capacity), location }); setMessage('Table updated.'); load(); } catch (error) { setMessage(errorText(error)); } }
  async function removeTable(id) { if (!window.confirm('Delete this table?')) return; try { await api.delete(`/tables/${id}`); setMessage('Table deleted.'); load(); } catch (error) { setMessage(errorText(error)); } }
  return <><div className="stats"><div><span>Total tables</span><strong>{tables.length}</strong></div><div><span>Selected day</span><strong>{reservations.length}</strong></div><div><span>Capacity</span><strong>{tables.reduce((sum, item) => sum + item.capacity, 0)}</strong></div></div><section className="admin-grid"><div className="panel"><p className="eyebrow">INVENTORY</p><h2>Manage tables</h2><form className="stack-form" onSubmit={addTable}><input required placeholder="Table number" type="number" value={form.tableNumber} onChange={e => setForm({ ...form, tableNumber: e.target.value })} /><input required placeholder="Capacity" type="number" value={form.capacity} onChange={e => setForm({ ...form, capacity: e.target.value })} /><input required placeholder="Location" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /><button className="primary">Add table</button></form>{message && <p className="alert">{message}</p>}<div className="small-list">{tables.map(table => <div key={table._id}><span>Table {table.tableNumber}<small>{table.capacity} seats · {table.location}</small></span><span><button className="text-button" onClick={() => updateTable(table)}>Edit</button> <button className="text-button" onClick={() => removeTable(table._id)}>Delete</button></span></div>)}</div></div><div className="panel"><div className="section-heading"><div><p className="eyebrow">SERVICE BOARD</p><h2>Reservations</h2></div><input type="date" value={date} onChange={e => setDate(e.target.value)} /></div>{reservations.length ? reservations.map(item => <div className="reservation-row" key={item._id}><div><strong>{item.startTime}–{item.endTime} · Table {item.table?.tableNumber}</strong><span>{item.customer?.name} · {item.customer?.email} · {item.partySize} guests</span></div><span className={`status ${item.status}`}>{item.status}</span></div>) : <p className="muted">No reservations for this day.</p>}</div></section></>;
}

export default function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('restaurant_user') || 'null')); const [refresh, setRefresh] = useState(0);
  function login(nextUser) { localStorage.setItem('restaurant_user', JSON.stringify(nextUser)); setUser(nextUser); }
  function logout() { localStorage.removeItem('restaurant_token'); localStorage.removeItem('restaurant_user'); setUser(null); }
  if (!user) return <Auth onLogin={login} />;
  return <div className="app-shell"><nav><div className="brand"><span>TT</span><strong>Table & Thyme</strong></div><div className="nav-user"><span>{user.name} <small>{user.role}</small></span><button className="text-button" onClick={logout}>Log out</button></div></nav><main className="content"><header className="page-header"><div><p className="eyebrow">{user.role === 'admin' ? 'ADMIN CONSOLE' : 'GOOD EVENING'}</p><h1>{user.role === 'admin' ? 'Run the room.' : 'Your next table awaits.'}</h1></div></header>{user.role === 'admin' ? <AdminHome /> : <CustomerHome refresh={refresh} setRefresh={setRefresh} />}</main></div>;
}
